window.todosOsProdutos = {
  maçaricos: [
    {
      id: 1,
      nome: 'MAÇARICO DE AQUECIMENTO (FS 43)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE AQUECIMENTO FS 43.png',
    },
    {
      id: 2,
      nome: 'MAÇARICO DE CORTE MANUAL (TAMANHO ESPECIAL 62)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL – TAMANHOS ESPECIAIS 62.png',
    },
    {
      id: 3,
      nome: 'MAÇARICO DE CORTE MANUAL (62)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 62.png',
    },
    {
      id: 4,
      nome: 'MAÇARICO DE CORTE MANUAL (142)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 142.png',
    },
    {
      id: 5,
      nome: 'MAÇARICO DE CORTE MANUAL (531+)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 531+.png',
    },
    {
      id: 6,
      nome: 'MAÇARICO DE CORTE MECANIZADO (198-2TF)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MECANIZADO 198-2TF.png',
    },
    {
      id: 7,
      nome: 'MAÇARICO DE SOLDA E BRASAGEM (50-10)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/maçaricos/MAÇARICO DE SOLDA E BRASAGEM 50-10.png',
    }
  ],
  reguladores: [
    {
      id: 8,
      nome: 'REG. DE ALTA PRESSÃO PARA CILINDRO (F-1100/F-950)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE ALTA PRESSÃO PARA CILINDRO – Ref F-1100  F-950.png',
    },
    {
      id: 9,
      nome: 'REGULADOR DE PRESSÃO (118)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 118.png',
    },
    {
      id: 10,
      nome: 'REGULADOR DE PRESSÃO (725)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 725.png',
    },
    {
      id: 11,
      nome: 'REGULADOR DE PRESSÃO (726)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 726.png',
    },
    {
      id: 12,
      nome: 'REGULADOR DE PRESSÃO (947)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 947.png',
    },
    {
      id: 13,
      nome: 'REGULADOR DE PRESSÃO (FS 94)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref FS 94.png',
    },
    {
      id: 14,
      nome: 'REGULADOR DE PRESSÃO PARA CILINDRO (925)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO PARA CILINDRO – Ref 925.png',
    },
    {
      id: 15,
      nome: 'REGULADOR DE VAZÃO (118)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 118.png',
    },
    {
      id: 16,
      nome: 'REGULADOR DE VAZÃO (725)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 725.png',
    },
    {
      id: 17,
      nome: 'REGULADOR DE VAZÃO (726)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 726.png',
    },
    {
      id: 18,
      nome: 'REGULADOR DE VAZÃO (947)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 947.png',
    },
    {
      id: 19,
      nome: 'REGULADOR DE VAZÃO (951)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 951.png',
    },
    {
      id: 20,
      nome: 'REGULADOR DE VAZÃO (FLOW)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref FLOW.png',
    },
    {
      id: 21,
      nome: 'REGULADOR DE VAZÃO PARA CILINDRO (925)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO PARA CILINDRO – Ref 925.png',
    }
  ],
  valvulas_e_maquinas: [
    {
      id: 22,
      nome: 'VÁL. CONTRA RETROCESSO DE CHAMA C/ ENGATE RÁP. (FBQC)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/válvulas/VÁLVULA CONTRA RETROCESSO DE CHAMA COM ENGATE RÁPIDO FBQC.png',
    },
    {
      id: 23,
      nome: 'VÁLVULA CONTRA RETROCESSO DE CHAMA (FB)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/válvulas/VÁLVULA CONTRA RETROCESSO DE CHAMA FB.png',
    },
    {
      id: 24,
      nome: 'VÁLVULA DE ENGATE RÁPIDO PARA GASES',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/válvulas/VÁLVULA DE ENGATE RÁPIDO PARA GASES.png',
    },
    {
      id: 25,
      nome: 'MÁQ. DE CORTE TARTARUGA SEMI AUTOMÁTICA (FS-MC-07)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/máquinas-de-corte/MÁQUINA DE CORTE TARTARUGA SEMI AUTOMÁTICA – Ref FS-MC-07.png',
    }
  ],
  acessórios: [
    {
      id: 26,
      nome: 'ACENDEDOR CENTELHADOR SPARK LIGHTER (1331-FS)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/ACENDEDOR CENTELHADOR SPARK LIGHTER – Ref 1331-FS.png',
    },
    {
      id: 27,
      nome: 'ADAPTADOR (2357-3)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/ADAPTADOR – Ref 2357-3.png',
    },
    {
      id: 28,
      nome: 'AGULHEIRO (LIMPADOR DE BICO)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/AGULHEIRO (LIMPADOR DE BICO).png',
    },
    {
      id: 29,
      nome: 'BICO VASSOURINHA ESTENDIDO (1021-1022)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/BICO VASSOURINHA ESTENDIDO – Ref 1021-1022.png',
    },
    {
      id: 30,
      nome: 'CAPA DE PRENSAGEM',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/CAPA DE PRENSAGEM.png',
    },
    {
      id: 31,
      nome: 'ESPIGÃO',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/ESPIGÃO.png',
    },
    {
      id: 32,
      nome: 'EXTENSOR (2393)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/EXTENSOR – Ref 2393.png',
    },
    {
      id: 33,
      nome: 'EXTENSOR (D-50-C)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/EXTENSOR – Ref D-50-C.png',
    },
    {
      id: 34,
      nome: 'MANGUEIRA PARA AR',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/MANGUEIRA PARA AR.png',
    },
    {
      id: 35,
      nome: 'MANGUEIRA',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/MANGUEIRA.png',
    },
    {
      id: 36,
      nome: 'MEDIDOR FLUXÔMETRO BIBIMETRO',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/MEDIDOR FLUXÔMETRO BIBIMETRO.png',
    },
    {
      id: 37,
      nome: 'MISTURADOR (F-43)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/MISTURADOR – Ref F-43.png',
    },
    {
      id: 38,
      nome: 'MISTURADOR (FS-19-2)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/MISTURADOR – Ref FS-19-2.png',
    },
    {
      id: 39,
      nome: 'PINO DE ENGATE RÁPIDO',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/PINO DE ENGATE RÁPIDO.png',
    },
    {
      id: 40,
      nome: 'PINOS DE CONEXÃO',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/PINOS DE CONEXÃO.png',
    },
    {
      id: 41,
      nome: 'PORCA DIREITA',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/PORCA DIREITA.png',
    },
    {
      id: 42,
      nome: 'PORCA ESQUERDA',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/PORCA ESQUERDA.png',
    },
    {
      id: 43,
      nome: 'REFIL DE PEDRAS C/ 5 PARA CENTELHADOR',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/acessórios/REFIL DE PEDRAS C5 PARA CENTELHADOR.png',
    }
  ],
  bicos: [
    {
      id: 44,
      nome: 'BICO DE AQUECIMENTO (1390-AC)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-AC.png',
    },
    {
      id: 45,
      nome: 'BICO DE AQUECIMENTO (1390-FS-A)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-FS-A.png',
    },
    {
      id: 46,
      nome: 'BICO DE AQUECIMENTO (1390-N)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-N.png',
    },
    {
      id: 47,
      nome: 'BICO DE AQUECIMENTO (2290-FS)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 2290-FS.png',
    },
    {
      id: 48,
      nome: 'BICO DE AQUECIMENTO (FS-62-P)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref FS-62-P.png',
    },
    {
      id: 49,
      nome: 'BICO DE CORTE (6290-AC)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-AC.png',
    },
    {
      id: 50,
      nome: 'BICO DE CORTE (6290-N-FS)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-N-FS.png',
    },
    {
      id: 51,
      nome: 'BICO DE CORTE (6290-NFF)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-NFF.png',
    },
    {
      id: 52,
      nome: 'BICO DE CORTE (6290-VVC)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-VVC.png',
    },
    {
      id: 53,
      nome: 'BICO DE CORTE DE ALTA PRECISÃO – AC. (1502)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE DE ALTA PRECISÃO – ACETILENO – Ref 1502.png',
    },
    {
      id: 54,
      nome: 'BICO DE CORTE ALTA PRECISÃO – GLP/GÁS NAT. (1503)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE CORTE DE ALTA PRECISÃO – GLP OU GÁS NATURAL – Ref 1503.png',
    },
    {
      id: 55,
      nome: 'BICO DE GOIVAGEM (6290-G)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE GOIVAGEM – Ref 6290-G.png',
    },
    {
      id: 56,
      nome: 'BICO DE GOIVAGEM (6290-GG)',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/bicos/BICO DE GOIVAGEM – Ref 6290-GG.png',
    }
  ],
  kits: [
    {
      id: 57,
      nome: 'KIT AQUECIMENTO GLP (45KG – INDUSTRIAL) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT AQUECIMENTO GLP (45KG – INDUSTRIAL) + O2.png',
    },
    {
      id: 58,
      nome: 'KIT AQUECIMENTO GLP (45KG – PRÁTICO) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT AQUECIMENTO GLP (45KG – PRÁTICO) + O2.png',
    },
    {
      id: 59,
      nome: 'KIT CORTE ACETILENO (300mm) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT CORTE ACETILENO (300mm) + O2.png',
    },
    {
      id: 60,
      nome: 'KIT CORTE GLP (13KG – 75mm) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT CORTE GLP (13KG – 75mm) + O2.png',
    },
    {
      id: 61,
      nome: 'KIT CORTE GLP (45KG – 75mm) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT CORTE GLP (45KG – 75mm) + O2.png',
    },
    {
      id: 62,
      nome: 'KIT CORTE GLP (45KG – 300mm) + O2',
      valor: 1000,
      desconto: 50,
      imagem: 'assets/produtos/kits/KIT CORTE GLP (45KG – 300mm) + O2.png',
    },
  ]
};
