window.todosOsProdutos = {
    maçaricos: [
        {
            id: 1,
            nome: 'MAÇARICO DE AQUECIMENTO (FS 43)',
            valor: 1042.86,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE AQUECIMENTO FS 43.webp',
        },
        {
            id: 2,
            nome: 'MAÇARICO DE CORTE MANUAL 530MM (62)',
            valor: 829.19,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 62.webp',
        },
        {
            id: 3,
            nome: 'MAÇARICO DE CORTE MANUAL 530MM (531+)',
            valor: 332.42,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 531+.webp',
        },
        {
            id: 4,
            nome: 'MAÇARICO DE CORTE MECANIZADO 460MM (198-2TF)',
            valor: 2095.63,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MECANIZADO 198-2TF.webp',
        },
        {
            id: 5,
            nome: 'MAÇARICO DE SOLDA E BRASAGEM (50-10)',
            valor: 774.34,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE SOLDA E BRASAGEM 50-10.webp',
        },
        {
            id: 6,
            nome: 'MAÇARICO DE CORTE MANUAL 440MM (142)',
            valor: 779.99,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL 142.webp',
        },
        {
            id: 7,
            nome: 'MAÇARICO DE CORTE MANUAL 1000MM (TAM. ESP. 62)',
            valor: 1308.81,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/maçaricos/MAÇARICO DE CORTE MANUAL – TAMANHOS ESPECIAIS 62.webp',
        }
    ],
    reguladores: [
        {
            id: 8,
            nome: 'REGULADOR DE PRESSÃO (118)',
            valor: 641.77,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 118.webp',
        },
        {
            id: 9,
            nome: 'REGULADOR DE PRESSÃO (725)',
            valor: 236,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 725.webp',
        },
        {
            id: 10,
            nome: 'REGULADOR DE PRESSÃO (726)',
            valor: 276.50,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 726.webp',
        },
        {
            id: 11,
            nome: 'REGULADOR DE PRESSÃO (947)',
            valor: 758.69,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref 947.webp',
        },
        {
            id: 12,
            nome: 'REGULADOR DE PRESSÃO (FS 94)',
            valor: 179,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO – Ref FS 94.webp',
        },
        {
            id: 13,
            nome: 'REGULADOR DE PRESSÃO PARA CILINDRO (925)',
            valor: 734.60,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE PRESSÃO PARA CILINDRO – Ref 925.webp',
        },
        {
            id: 14,
            nome: 'REGULADOR DE VAZÃO (118)',
            valor: 641.77,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 118.webp',
        },
        {
            id: 15,
            nome: 'REGULADOR DE VAZÃO (725)',
            valor: 236,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 725.webp',
        },
        {
            id: 16,
            nome: 'REGULADOR DE VAZÃO (726)',
            valor: 317.68,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 726.webp',
        },
        {
            id: 17,
            nome: 'REGULADOR DE VAZÃO (947)',
            valor: 758.69,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 947.webp',
        },
        {
            id: 18,
            nome: 'REGULADOR DE VAZÃO (951)',
            valor: 576.47,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref 951.webp',
        },
        {
            id: 19,
            nome: 'REGULADOR DE VAZÃO (FLOW)',
            valor: 133.82,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO – Ref FLOW.webp',
        },
        {
            id: 20,
            nome: 'REGULADOR DE VAZÃO PARA CILINDRO (925)',
            valor: 544.41,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE VAZÃO PARA CILINDRO – Ref 925.webp',
        },
        {
            id: 21,
            nome: 'REG. DE ALTA PRESSÃO PARA CILINDRO (F-1100/F-950)',
            valor: 2525.40,
            desconto: 40,
            unidade_medida: 'un',
            imagem: 'assets/produtos/reguladores/REGULADOR DE ALTA PRESSÃO PARA CILINDRO – Ref F-1100  F-950.webp',
        },
    ],
    bicos: [
        {
            id: 44,
            nome: 'BICO DE AQUECIMENTO (1390-AC)',
            valor: 56.32,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-AC.webp',
        },
        {
            id: 45,
            nome: 'BICO DE AQUECIMENTO (1390-FS-A)',
            valor: 56.32,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-FS-A.webp',
        },
        {
            id: 46,
            nome: 'BICO DE AQUECIMENTO (1390-N)',
            valor: 56.32,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 1390-N.webp',
        },
        {
            id: 47,
            nome: 'BICO DE AQUECIMENTO (2290-FS)',
            valor: 646.85,
            desconto: 35,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref 2290-FS.webp',
        },
        {
            id: 48,
            nome: 'BICO DE AQUECIMENTO (FS-62-P)',
            valor: 351.37,
            desconto: 30,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE AQUECIMENTO – Ref FS-62-P.webp',
        },
        {
            id: 49,
            nome: 'BICO DE CORTE (6290-AC)',
            valor: 51.02,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-AC.webp',
        },
        {
            id: 50,
            nome: 'BICO DE CORTE (6290-N-FS)',
            valor: 93.13,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-N-FS.webp',
        },
        {
            id: 51,
            nome: 'BICO DE CORTE (6290-NFF)',
            valor: 51.02,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-NFF.webp',
        },
        {
            id: 52,
            nome: 'BICO DE CORTE (6290-VVC)',
            valor: 68,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE – Ref 6290-VVC.webp',
        },
        {
            id: 53,
            nome: 'BICO DE CORTE DE ALTA PRECISÃO – AC. (1502)',
            valor: 47.80,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE DE ALTA PRECISÃO – ACETILENO – Ref 1502.webp',
        },
        {
            id: 54,
            nome: 'BICO DE CORTE ALTA PRECISÃO – GLP/GÁS NAT. (1503)',
            valor: 27.28,
            desconto: 5,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE CORTE DE ALTA PRECISÃO – GLP OU GÁS NATURAL – Ref 1503.webp',
        },
        {
            id: 55,
            nome: 'BICO DE GOIVAGEM (6290-G)',
            valor: 114.80,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE GOIVAGEM – Ref 6290-G.webp',
        },
        {
            id: 56,
            nome: 'BICO DE GOIVAGEM (6290-GG)',
            valor: 114,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/bicos/BICO DE GOIVAGEM – Ref 6290-GG.webp',
        }
    ],
    valvulas_e_maquinas: [
        {
            id: 22,
            nome: 'VÁL. CONTRA RETROCESSO DE CHAMA C/ ENGATE RÁP. (FBQC)',
            valor: 244.22,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/válvulas/VÁLVULA CONTRA RETROCESSO DE CHAMA COM ENGATE RÁPIDO FBQC.webp',
        },
        {
            id: 23,
            nome: 'VÁLVULA CONTRA RETROCESSO DE CHAMA (FB)',
            valor: 43.65,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/válvulas/VÁLVULA CONTRA RETROCESSO DE CHAMA FB.webp',
        },
        {
            id: 24,
            nome: 'VÁLVULA DE ENGATE RÁPIDO PARA GASES',
            valor: 101.56,
            desconto: 15,
            unidade_medida: 'un',
            imagem: 'assets/produtos/válvulas/VÁLVULA DE ENGATE RÁPIDO PARA GASES.webp',
        },
        {
            id: 25,
            nome: 'MÁQ. DE CORTE TARTARUGA SEMI AUTOMÁTICA (FS-MC-07)',
            valor: 2985.00,
            desconto: 45,
            unidade_medida: 'un',
            imagem: 'assets/produtos/máquinas-de-corte/MÁQUINA DE CORTE TARTARUGA SEMI AUTOMÁTICA – Ref FS-MC-07.webp',
        }
    ],
    acessórios: [
        {
            id: 26,
            nome: 'ACENDEDOR CENTELHADOR SPARK LIGHTER (1331-FS)',
            valor: 17.64,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/ACENDEDOR CENTELHADOR SPARK LIGHTER – Ref 1331-FS.webp',
        },
        {
            id: 27,
            nome: 'ADAPTADOR (2357-3)',
            valor: 56,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/ADAPTADOR – Ref 2357-3.webp',
        },
        {
            id: 28,
            nome: 'AGULHEIRO (LIMPADOR DE BICO)',
            valor: 24.84,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/AGULHEIRO (LIMPADOR DE BICO).webp',
        },
        {
            id: 29,
            nome: 'BICO VASSOURINHA ESTENDIDO (1021-1022)',
            valor: 41.33,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/BICO VASSOURINHA ESTENDIDO – Ref 1021-1022.webp',
        },
        {
            id: 30,
            nome: 'CAPA DE PRENSAGEM',
            valor: 8.77,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/CAPA DE PRENSAGEM.webp',
        },
        {
            id: 31,
            nome: 'NIPLE/ESPIGÃO',
            valor: 8.33,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/ESPIGÃO.webp',
        },
        {
            id: 32,
            nome: 'EXTENSOR 915MM (2393)',
            valor: 492.48,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/EXTENSOR – Ref 2393.webp',
        },
        {
            id: 33,
            nome: 'EXTENSOR (D-50-C)',
            valor: 67.27,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/EXTENSOR – Ref D-50-C.webp',
        },
        {
            id: 34,
            nome: 'MANGUEIRA PARA AR 3/8" 9,5MM',
            valor: 27,
            desconto: 10,
            unidade_medida: 'mts',
            imagem: 'assets/produtos/acessórios/MANGUEIRA PARA AR.webp',
        },
        {
            id: 35,
            nome: 'MANGUEIRA 5/6" 8MM',
            valor: 20.44,
            desconto: 10,
            unidade_medida: 'mts',
            imagem: 'assets/produtos/acessórios/MANGUEIRA.webp',
        },
        {
            id: 36,
            nome: 'MEDIDOR FLUXÔMETRO BIBIMETRO',
            valor: 51.48,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/MEDIDOR FLUXÔMETRO BIBIMETRO.webp',
        },
        {
            id: 37,
            nome: 'MISTURADOR (F-43)',
            valor: 123.12,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/MISTURADOR – Ref F-43.webp',
        },
        {
            id: 38,
            nome: 'MISTURADOR (FS-19-2)',
            valor: 107.10,
            desconto: 20,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/MISTURADOR – Ref FS-19-2.webp',
        },
        {
            id: 39,
            nome: 'PINO DE ENGATE RÁPIDO',
            valor: 31.49,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/PINO DE ENGATE RÁPIDO.webp',
        },
        {
            id: 40,
            nome: 'PINOS DE CONEXÃO',
            valor: 31.49,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/PINOS DE CONEXÃO.webp',
        },
        {
            id: 41,
            nome: 'PORCA DIREITA',
            valor: 8.33,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/PORCA DIREITA.webp',
        },
        {
            id: 42,
            nome: 'PORCA ESQUERDA',
            valor: 8.33,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/PORCA ESQUERDA.webp',
        },
        {
            id: 43,
            nome: 'REFIL DE PEDRAS C/ 5 PARA CENTELHADOR',
            valor: 6.62,
            desconto: 10,
            unidade_medida: 'un',
            imagem: 'assets/produtos/acessórios/REFIL DE PEDRAS C5 PARA CENTELHADOR.webp',
        }
    ],
    kits: [
        {
            id: 57,
            nome: 'KIT AQUECIMENTO GLP (45KG – INDUSTRIAL) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT AQUECIMENTO GLP (45KG – INDUSTRIAL) + O2.webp',
        },
        {
            id: 58,
            nome: 'KIT AQUECIMENTO GLP (45KG – PRÁTICO) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT AQUECIMENTO GLP (45KG – PRÁTICO) + O2.webp',
        },
        {
            id: 59,
            nome: 'KIT CORTE GLP (45KG – 75mm) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT CORTE GLP (45KG – 75mm) + O2.webp',
        },
        {
            id: 60,
            nome: 'KIT CORTE GLP (45KG – 300mm) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT CORTE GLP (45KG – 300mm) + O2.webp',
        },
        {
            id: 61,
            nome: 'KIT CORTE ACETILENO (300mm) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT CORTE ACETILENO (300mm) + O2.webp',
        },
        {
            id: 62,
            nome: 'KIT CORTE GLP (13KG – 75mm) + O2',
            valor: 9000,
            desconto: 0,
            unidade_medida: 'un',
            imagem: 'assets/produtos/kits/KIT CORTE GLP (13KG – 75mm) + O2.webp',
        },
    ]
};